webtalk_init -webtalk_dir C:/Users/labella/Documents/ece212_labell_borek/lab09/lab09/lab09.sim/sim_1/behav/xsim/xsim.dir/control_fsm_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 12 14:29:29 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f55a6660-2f7c-4868-ae9f-f2d207d954de" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "37f6236e004a46ed9916f825b3ab612b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3912 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "196 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6464_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2024345826 -regid "" -xml C:/Users/labella/Documents/ece212_labell_borek/lab09/lab09/lab09.sim/sim_1/behav/xsim/xsim.dir/control_fsm_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/labella/Documents/ece212_labell_borek/lab09/lab09/lab09.sim/sim_1/behav/xsim/xsim.dir/control_fsm_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/labella/Documents/ece212_labell_borek/lab09/lab09/lab09.sim/sim_1/behav/xsim/xsim.dir/control_fsm_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
