# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/labella/Documents/ece212_labell_borek/lab11/.Xil/Vivado-12016-ECE419-92RS0Q2/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a100tcsg324-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {{C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv}} {
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/adder.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/alu.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/mips_decls_p.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/aludec.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/controller.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/datapath.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/dmem.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/imem.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/maindec.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/mips.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/mux2.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/pr_d_e.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/pr_e_m.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/pr_f_d.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/pr_m_w.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/pr_pc.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/regfile.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/signext.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/sl2.sv}
      {C:/Users/labella/Documents/ece212_labell_borek/source directories/mips_L_pipeline-master/mips_L_pipeline-master/sv/top.sv}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/labella/Documents/ece212_labell_borek/lab11/.Xil/Vivado-12016-ECE419-92RS0Q2/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
